name = "ViewerGL"
uuid = "f3ad01d2-8ff6-11e9-2fbf-a74e184a468e"
authors = ["apaoluzzi <apaoluzzi@mac.com>"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
