name = "ViewerGL"
uuid = "32496ab8-9004-11e9-0205-c9e71bda7ab0"
authors = ["apaoluzzi <apaoluzzi@mac.com>"]
version = "0.1.0"

# [deps]
# ViewGL = "e4b09d3c-965a-11e9-064b-1f4b25cc26ee"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
